### ISSUE TITLE
Current pull requests to upstream

### ISSUE THREAD

**Issue by kalifg** [ChessCom/alice#6]
## Reference

ChessCom/chess#1340
## Waiting to be merged
- [x] nelmio/alice#86 - Enable fixture inheritance
- [x] nelmio/alice#87 - Add `@self` reference
- [x] nelmio/alice#88 - Provider reference passing update
